### ISSUE TITLE
pmaint regen: weird failures when multiple ebuilds die during metadata regen

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcore#120]
As observed e.g. in lisp overlay:

```
!!! ERROR: app-emacs/geiser-999 failed.
!!! die invoked from directory /home/mgorny/pkgcore-venv/lib/pkgcore
!!! Call stack:
!!!             ebuild-daemon.bash, line 458:  Called __ebd_exec_main 'daemonize'
!!!             ebuild-daemon.bash, line 210:  Called __ebd_main_loop
!!!             ebuild-daemon.bash, line 441:  Called __ebd_process_metadata '157' 'depend'
!!!             ebuild-daemon.bash, line 374:  Called __execute_phases 'depend'
!!!                     ebuild.lib, line 431:  Called __load_ebuild '/home/mgorny/repos/lisp/app-emacs/geiser/geiser-999.ebuild'
!!!                     ebuild.lib, line 252:  Called __qa_invoke 'source' '/home/mgorny/repos/lisp/app-emacs/geiser/geiser-999.ebuild'
!!!         isolated-functions.lib, line 286:  Called source '/home/mgorny/repos/lisp/app-emacs/geiser/geiser-999.ebuild'
!!!              geiser-999.ebuild, line  12:  Called inherit 'git'
!!!   ebuild-default-functions.lib, line 230:  Called __internal_inherit 'git'
!!!              ebuild-daemon.lib, line  35:  Called die
!!! The die message:
!!!  inherit for git failed


!!! ERROR: app-emacs/slime-2.0_p20130214 failed.
!!! die invoked from directory /home/mgorny/pkgcore-venv/lib/pkgcore
!!! Call stack:
!!!             ebuild-daemon.bash, line 458:  Called __ebd_exec_main 'daemonize'
!!!             ebuild-daemon.bash, line 210:  Called __ebd_main_loop
!!!             ebuild-daemon.bash, line 441:  Called __ebd_process_metadata '206' 'depend'
!!!             ebuild-daemon.bash, line 374:  Called __execute_phases 'depend'
!!!                     ebuild.lib, line 431:  Called __load_ebuild '/home/mgorny/repos/lisp/app-emacs/slime/slime-2.0_p20130214.ebuild'
!!!                     ebuild.lib, line 252:  Called __qa_invoke 'source' '/home/mgorny/repos/lisp/app-emacs/slime/slime-2.0_p20130214.ebuild'
!!!         isolated-functions.lib, line 286:  Called source '/home/mgorny/repos/lisp/app-emacs/slime/slime-2.0_p20130214.ebuild'
!!!     slime-2.0_p20130214.ebuild, line   7:  Called inherit 'common-lisp-3' 'elisp' 'eutils'
!!!   ebuild-default-functions.lib, line 230:  Called __internal_inherit 'elisp'
!!!              ebuild-daemon.lib, line  37:  Called die
!!! The die message:
!!!  unknown inherit command from pythonic side, 'gen_metadata 161' for eclass elisp

received unknown com: export CATEGORY='app-emacs' PR=r0 PVR='2.11' PV='2.11' EBUILD='/home/mgorny/repos/lisp/app-emacs/slime/slime-2.11.ebuild' P='slime-2.11' PF='slime-2.11' PN=slimepath
!!! caught exception inherit requires an unknown eclass, git cannot be found while processing ebuild src: app-emacs/geiser-999
ERROR pkgcore: returned val from gen_metadata was 'False'
!!! caught exception False while processing ebuild src: app-emacs/slime-2.0_p20130214
ERROR pkgcore: returned val from gen_metadata was 'False'
!!! caught exception False while processing ebuild src: app-emacs/slime-2.11
!!! caught exception ("Expected command; instead got nothing from ''", None) while processing ebuild src: app-emacs/slime-2.12
Traceback (most recent call last):
  File "/home/mgorny/pkgcore-venv/bin/pmaint", line 4, in <module>
    scripts.main(basename(__file__))
  File "/home/mgorny/pkgcore-venv/lib/python2.7/site-packages/pkgcore/scripts/__init__.py", line 43, in main
    commandline.main(subcommands)
  File "/home/mgorny/pkgcore-venv/lib/python2.7/site-packages/pkgcore/util/commandline.py", line 915, in main
    exitstatus = main_func(options, out, err)
  File "/home/mgorny/pkgcore-venv/lib/python2.7/site-packages/pkgcore/scripts/pmaint.py", line 272, in regen_main
    eclass_caching=(not options.disable_eclass_caching))
  File "/home/mgorny/pkgcore-venv/lib/python2.7/site-packages/pkgcore/operations/__init__.py", line 68, in _recast_exception_decorator
    return functor(*args, **kwds)
  File "/home/mgorny/pkgcore-venv/lib/python2.7/site-packages/pkgcore/operations/repo.py", line 236, in _cmd_api_regen_cache
    self._get_observer(observer), threads=threads, **options)
  File "/home/mgorny/pkgcore-venv/lib/python2.7/site-packages/pkgcore/operations/regen.py", line 41, in regen_repository
    regen_iter(passthru(repo), _get_repo_helper(), observer)
  File "/home/mgorny/pkgcore-venv/lib/python2.7/site-packages/pkgcore/operations/regen.py", line 15, in regen_iter
    regen_func(x)
  File "/home/mgorny/pkgcore-venv/lib/python2.7/site-packages/pkgcore/ebuild/repository.py", line 529, in __call__
    return pkg._fetch_metadata(ebp=self.ebp, force_regen=self.force)
  File "/home/mgorny/pkgcore-venv/lib/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py", line 269, in _fetch_metadata
    return self._parent._get_metadata(self, ebp=ebp, force_regen=force_regen)
  File "/home/mgorny/pkgcore-venv/lib/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py", line 360, in _get_metadata
    return self._update_metadata(pkg, ebp=ebp)
  File "/home/mgorny/pkgcore-venv/lib/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py", line 368, in _update_metadata
    mydata = my_proc.get_keys(pkg, self._ecache)
  File "/home/mgorny/pkgcore-venv/lib/python2.7/site-packages/pkgcore/ebuild/processor.py", line 825, in get_keys
    {"key": receive_key})
  File "/home/mgorny/pkgcore-venv/lib/python2.7/site-packages/pkgcore/ebuild/processor.py", line 758, in _run_depend_like_phase
    self.write("%s %i\n%s" % (command, len(data), data), append_newline=False)
  File "/home/mgorny/pkgcore-venv/lib/python2.7/site-packages/pkgcore/ebuild/processor.py", line 456, in write
    raise RuntimeError(ie)
RuntimeError: [Errno 32] Broken pipe
 * Cache regen failed with 1
```

**Comment by mgorny** [comment]
Now, the following are my observations/suspicions not supported by a code review ;). I think this is ebd being unable to recover after ebuild dying during metadata gen. Looks like it misinterprets the input following the failure. If I use more threads for the regen (output above is for single thread), more ebuilds die properly before the issue happens.

**Comment by mgorny** [comment]
@ferringb, any chance you could help us with that? I've been trying to debug but with no success. There's too much indirection and cross-magic for me to figure out what's even really happening.

**Comment by radhermit** [comment]
Closing since I'm going to guess that this was fixed when I IPC-ed die calls and improved regen errors. If not, feel free to reopen with updated info.
