### ISSUE TITLE
crash with pkgcore.config.errors.ConfigurationError: Type of 'usersync' unknown

### ISSUE THREAD

**Issue by oz123** [pkgcore/pkgcore#257]
I am sorry if this bug more of a configuration issue. Until now I happily used pkgcore, but recent git update borked it.

```
 $ pmerge 
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/pkgcore/config/central.py", line 395, in collapse_named_section
    result = self.collapse_section(section_stack, name)
  File "/usr/lib64/python3.6/site-packages/pkgcore/config/central.py", line 475, in collapse_section
    collapsed = CollapsedConfig(type_obj, self._render_config_stack(type_obj, config_stack),
  File "/usr/lib64/python3.6/site-packages/pkgcore/config/central.py", line 497, in _render_config_stack
    raise errors.ConfigurationError(f'Type of {key!r} unknown')
pkgcore.config.errors.ConfigurationError: Type of 'usersync' unknown

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/pkgcore/config/central.py", line 547, in get_default
    defaults = self.types.get(type_name, {}).items()
  File "/usr/lib64/python3.6/site-packages/snakeoil/klass.py", line 171, in __get__
    obj = self.function(instance)
  File "/usr/lib64/python3.6/site-packages/pkgcore/config/central.py", line 485, in types
    obj = self.collapse_named_section(name)
  File "/usr/lib64/python3.6/site-packages/pkgcore/config/central.py", line 401, in collapse_named_section
    f'Collapsing section named {name!r}') from e
pkgcore.config.errors.ConfigurationError: Collapsing section named 'sync:gentoo'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/pmerge", line 4, in <module>
    scripts.run(basename(__file__))
  File "/usr/lib64/python3.6/site-packages/pkgcore/scripts/__init__.py", line 32, in run
    sys.exit(tool())
  File "/usr/lib64/python3.6/site-packages/snakeoil/cli/tool.py", line 83, in __call__
    ret = self.main()
  File "/usr/lib64/python3.6/site-packages/snakeoil/cli/tool.py", line 168, in main
    self.handle_exec_exception(e)
  File "/usr/lib64/python3.6/site-packages/snakeoil/cli/tool.py", line 152, in main
    self.options, func = self.parse_args(args=self.args, namespace=self.options)
  File "/usr/lib64/python3.6/site-packages/snakeoil/cli/tool.py", line 103, in parse_args
    options = self.parser.parse_args(args=args, namespace=namespace)
  File "/usr/lib64/python3.6/site-packages/snakeoil/cli/arghparse.py", line 1083, in parse_args
    delayed(args, attr)
  File "/usr/lib64/python3.6/site-packages/snakeoil/cli/arghparse.py", line 318, in __call__
    self.invokable(namespace, attr)
  File "/usr/lib64/python3.6/site-packages/pkgcore/util/commandline.py", line 224, in store_default
    obj = config.get_default(config_type)
  File "/usr/lib64/python3.6/site-packages/pkgcore/config/central.py", line 552, in get_default
    f'Collapsing defaults for {type_name!r}') from e
pkgcore.config.errors.ConfigurationError: Collapsing defaults for 'domain'
```

`grep -r usersync /etc/portage/` shows nothing.

This is probably my problem, but the error isn't helping me find it.

**Comment by radhermit** [comment]
What version of pkgcore are you running, i.e. pmerge --version?

**Comment by oz123** [comment]
```
oznt@yeni2 ~ $ pmerge --version
pkgcore 0.10.0-748-g2499f74 -- Mon, 4 Feb 2019 18:32:14 -0600
```

I installed it via: `emerge =sys-apps/pkgcore-9999`
