### ISSUE TITLE
glsa parsing: AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcore#269]
CI just started failing with the following traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/pkgcheck", line 4, in <module>
    scripts.run(basename(__file__))
  File "/usr/lib64/python3.6/site-packages/pkgcheck/scripts/__init__.py", line 30, in run
    sys.exit(tool())
  File "/usr/lib64/python3.6/site-packages/snakeoil/cli/tool.py", line 86, in __call__
    ret = self.main()
  File "/usr/lib64/python3.6/site-packages/snakeoil/cli/tool.py", line 189, in main
    self.handle_exec_exception(e)
  File "/usr/lib64/python3.6/site-packages/snakeoil/cli/tool.py", line 174, in main
    exitstatus = func(self.options, self.out, self.err)
  File "/usr/lib64/python3.6/site-packages/pkgcheck/scripts/pkgcheck.py", line 443, in _scan
    for result in pipe.start():
  File "/usr/lib64/python3.6/site-packages/pkgcheck/base.py", line 507, in start
    reports = check.start()
  File "/usr/lib64/python3.6/site-packages/pkgcheck/checks/glsa.py", line 107, in start
    for r in GlsaDirSet(self.glsa_dir):
  File "/usr/lib64/python3.6/site-packages/pkgcore/pkgsets/glsa.py", line 57, in __iter__
    for glsa, catpkg, pkgatom, vuln in self.iter_vulnerabilities():
  File "/usr/lib64/python3.6/site-packages/pkgcore/pkgsets/glsa.py", line 102, in iter_vulnerabilities
    pkg, tag="glsa(%s)" % fn[5:-4])
  File "/usr/lib64/python3.6/site-packages/pkgcore/pkgsets/glsa.py", line 139, in generate_intersects_from_pkg_node
    for x in invuln]
  File "/usr/lib64/python3.6/site-packages/pkgcore/pkgsets/glsa.py", line 139, in <listcomp>
    for x in invuln]
  File "/usr/lib64/python3.6/site-packages/pkgcore/pkgsets/glsa.py", line 150, in generate_restrict_from_range
    base = str(node.text.strip())
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by radhermit** [comment]
Looks like https://gitweb.gentoo.org/data/glsa.git/commit/?id=9aae8f60135672abdd944bb9cc8f232884648045 fixed it. I'll try to make the parsing more robust and report parsing errors while rolling along similar to other file handling work I've done.

**Comment by radhermit** [comment]
Actually we probably should just ignore the errors and add a schema check for glsa xml files since I assume that should catch issues like this.
