### ISSUE TITLE
pmerge -DNavu @world crashes

### ISSUE THREAD

**Issue by lovesegfault** [pkgcore/pkgcore#273]
```
❯ pmerge -DNavu @world
 * Scanning for changed USE...
 * Resolving...
[ebuild     U  ] sys-devel/gcc-9.2.0-r1:9.2.0::gentoo [9.2.0:9.2.0::gentoo] USE="(cxx) fortran graphite lto (multilib) nls nptl openmp pch pgo (pie) sanitize ssp vtv (-altivec) -d -debug -doc (-fixed-point) -go (-hardened) (-jit) (-libssp) -objc -objc++ -objc-gc -systemtap -test -vanilla" 15.1 KiB
[ebuild  NS    ] cross-avr/gcc-9.2.0-r1:9.2.0::crossdev [8.3.0-r1:8.3.0] USE="cxx jit (multilib) nls nptl openmp pch (-altivec) -d -debug -doc (-fixed-point) -fortran -go -graphite -hardened -libssp -lto -objc -objc++ -objc-gc -pgo -pie -sanitize -ssp -systemtap -test -vanilla -vtv"

Total: 2 packages (1 upgrade, 1 in new slot), Size of downloads: 15.1 KiB


 * Running sanity checks...
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/pmerge", line 4, in <module>
    scripts.run(basename(__file__))
  File "/usr/lib64/python3.6/site-packages/pkgcore/scripts/__init__.py", line 34, in run
    sys.exit(tool())
  File "/usr/lib64/python3.6/site-packages/snakeoil/cli/tool.py", line 79, in __call__
    ret = self.main()
  File "/usr/lib64/python3.6/site-packages/snakeoil/cli/tool.py", line 182, in main
    self.handle_exec_exception(e)
  File "/usr/lib64/python3.6/site-packages/snakeoil/cli/tool.py", line 167, in main
    exitstatus = func(self.options, self.out, self.err)
  File "/usr/lib64/python3.6/site-packages/pkgcore/scripts/pmerge.py", line 828, in main
    sanity_failures = run_sanity_checks((x.pkg for x in changes), domain, threads=1)
  File "/usr/lib64/python3.6/site-packages/pkgcore/ebuild/misc.py", line 579, in run_sanity_checks
    for pkg, failed in executor.map(sanity_check, _filter_pkgs(pkgs)):
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib64/python3.6/site-packages/pkgcore/ebuild/misc.py", line 569, in <lambda>
    sanity_check = lambda pkg_ops: pkg_ops.sanity_check()
  File "/usr/lib64/python3.6/site-packages/pkgcore/operations/__init__.py", line 69, in _recast_exception_decorator
    return functor(*args, **kwds)
  File "/usr/lib64/python3.6/site-packages/pkgcore/operations/format.py", line 103, in _cmd_api_sanity_check
    return self._cmd_implementation_sanity_check(self.domain)
  File "/usr/lib64/python3.6/site-packages/pkgcore/ebuild/ebd.py", line 906, in _cmd_implementation_sanity_check
    result = check(self, self.pkg, domain=domain)
  File "/usr/lib64/python3.6/site-packages/pkgcore/ebuild/ebd.py", line 953, in _check_pkg_pretend
    userpriv=True, sandbox=True, extra_handlers=commands)
  File "/usr/lib64/python3.6/site-packages/pkgcore/ebuild/ebd.py", line 473, in run_generic_phase
    ebd = request_ebuild_processor(userpriv=userpriv, sandbox=sandbox, fd_pipes=fd_pipes)
  File "/usr/lib64/python3.6/site-packages/pkgcore/ebuild/processor.py", line 52, in _inner
    return functor(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/pkgcore/ebuild/processor.py", line 102, in request_ebuild_processor
    if not ebp.is_alive:
  File "/usr/lib64/python3.6/site-packages/pkgcore/ebuild/processor.py", line 650, in is_alive
    if self.expect("yep!", timeout=10):
  File "/usr/lib64/python3.6/site-packages/pkgcore/ebuild/processor.py", line 488, in expect
    signal.signal(signal.SIGALRM, self._timeout_ebp)
  File "/usr/lib64/python3.6/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
Sandboxed process killed by signal: Broken pipe
```

**Comment by radhermit** [comment]
Fixed in https://github.com/pkgcore/pkgcore/commit/73ff290927812df63c86f29015362034c0fa8166.
