### ISSUE TITLE
pmege does not understand sets of sets

### ISSUE THREAD

**Issue by bgloyer** [pkgcore/pkgcore#280]
pmerge fails if a set contains a set.

$pmerge -p @weekly
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.7/pmerge", line 4, in <module>
    scripts.run(basename(__file__))
  File "/usr/lib/python3.7/site-packages/pkgcore/scripts/__init__.py", line 34, in run
    sys.exit(tool())
  File "/usr/lib/python3.7/site-packages/snakeoil/cli/tool.py", line 79, in __call__
    ret = self.main()
  File "/usr/lib/python3.7/site-packages/snakeoil/cli/tool.py", line 182, in main
    self.handle_exec_exception(e)
  File "/usr/lib/python3.7/site-packages/snakeoil/cli/tool.py", line 167, in main
    exitstatus = func(self.options, self.out, self.err)
  File "/usr/lib/python3.7/site-packages/pkgcore/scripts/pmerge.py", line 632, in main
    l = list(pkgset)
  File "/usr/lib/python3.7/site-packages/pkgcore/pkgsets/filelist.py", line 53, in __iter__
    return iter(self._atoms)
  File "/usr/lib/python3.7/site-packages/snakeoil/klass.py", line 174, in __get__
    obj = self.function(instance)
  File "/usr/lib/python3.7/site-packages/pkgcore/pkgsets/filelist.py", line 40, in _atoms
    (x, self.path))
ValueError: set @myset isn't a valid atom in pkgset '/etc/portage/sets/weekly'

$ cat /etc/portage/sets/weekly 
@myset
@system
@profile

Also --clean wants to remove every package in @myset
$ 'pmerge -p --clean'
 . . . . .
removing 520 packages of 1148 installed, 45.30%.

**Comment by radhermit** [comment]
I'm sorry, but since package sets aren't in any official spec that I'm aware of I don't see this getting fixed without someone else doing the legwork. In other words, I don't enjoy reading portage source code to try to remain compatible with portage features I don't use.

**Comment by ferringb** [comment]
@bgloyer your ask is addressable, but it's problematic since portage tends to do things w/out coordination; point blank, they tend to do things without concern for pkgcore leaving pkgcore broken (a pattern since when pkgcore was portage v3).  That's our problem, not yours, but it impacts your ask.

If you can break your ask down into something more constrained- for example, "this is how portage parses this"- that makes it easier on our end to do something.  If you break out the constraints, we can write tests and be willing to support the feature, basically.
