### ISSUE TITLE
OSError: [Errno 24] Too many open files ; when regenerating a large repo

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcore#296]
```pytb
$ time pmaint regen -t 16 --force --use-local-desc --pkg-desc-index -vvv ros-overlay
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.9/pmaint", line 4, in <module>
    scripts.run(basename(__file__))
  File "/usr/lib/python3.9/site-packages/pkgcore/scripts/__init__.py", line 32, in run
    sys.exit(tool())
  File "/usr/lib/python3.9/site-packages/snakeoil/cli/tool.py", line 79, in __call__
    ret = self.main()
  File "/usr/lib/python3.9/site-packages/snakeoil/cli/tool.py", line 185, in main
    self.handle_exec_exception(e)
  File "/usr/lib/python3.9/site-packages/snakeoil/cli/tool.py", line 170, in main
    exitstatus = func(self.options, self.out, self.err)
  File "/usr/lib/python3.9/site-packages/pkgcore/scripts/pmaint.py", line 314, in regen_main
    ret.append(repo.operations.regen_cache(
  File "/usr/lib/python3.9/site-packages/pkgcore/operations/__init__.py", line 69, in _recast_exception_decorator
    return functor(*args, **kwds)
  File "/usr/lib/python3.9/site-packages/pkgcore/operations/repo.py", line 252, in _cmd_api_regen_cache
    pkgs = frozenset(pkg.cpvstr for pkg in self.repo)
  File "/usr/lib/python3.9/site-packages/pkgcore/operations/repo.py", line 252, in <genexpr>
    pkgs = frozenset(pkg.cpvstr for pkg in self.repo)
  File "/usr/lib/python3.9/site-packages/pkgcore/repository/prototype.py", line 297, in _internal_match
    for pkg in self._internal_gen_candidates(candidates, **kwargs):
  File "/usr/lib/python3.9/site-packages/pkgcore/repository/prototype.py", line 294, in _internal_gen_candidates
    yield from sorter(pkg_filter(pkgs))
  File "/usr/lib/python3.9/site-packages/pkgcore/ebuild/repository.py", line 557, in _pkg_filter
    pkg.data
  File "/usr/lib/python3.9/site-packages/pkgcore/package/base.py", line 97, in dynamic_getattr_dict
    val = functor(self)
  File "/usr/lib/python3.9/site-packages/pkgcore/package/metadata.py", line 50, in data
    return self._fetch_metadata()
  File "/usr/lib/python3.9/site-packages/pkgcore/ebuild/ebuild_src.py", line 352, in _fetch_metadata
    return self._parent._get_metadata(self, ebp=ebp, force_regen=force_regen)
  File "/usr/lib/python3.9/site-packages/pkgcore/ebuild/ebuild_src.py", line 441, in _get_metadata
    return self._update_metadata(pkg, ebp=ebp)
  File "/usr/lib/python3.9/site-packages/pkgcore/ebuild/ebuild_src.py", line 448, in _update_metadata
    with processor.reuse_or_request(ebp) as my_proc:
  File "/usr/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.9/site-packages/pkgcore/ebuild/processor.py", line 169, in reuse_or_request
    ebp = request_ebuild_processor(**kwargs)
  File "/usr/lib/python3.9/site-packages/pkgcore/ebuild/processor.py", line 49, in _inner
    return functor(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pkgcore/ebuild/processor.py", line 107, in request_ebuild_processor
    ebp = EbuildProcessor(userpriv, sandbox, fd_pipes=fd_pipes)
  File "/usr/lib/python3.9/site-packages/pkgcore/ebuild/processor.py", line 352, in __init__
    dread, dwrite = os.pipe()
OSError: [Errno 24] Too many open files
Exception ignored in: <function EbuildProcessor.__del__ at 0x7ff6462de5e0>
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pkgcore/ebuild/processor.py", line 778, in __del__
    if self.is_responsive:
  File "/usr/lib/python3.9/site-packages/pkgcore/ebuild/processor.py", line 683, in is_responsive
    if self.is_alive:
  File "/usr/lib/python3.9/site-packages/pkgcore/ebuild/processor.py", line 666, in is_alive
    current_pid = self.pid
AttributeError: 'EbuildProcessor' object has no attribute 'pid'

real	3m8,527s
user	0m30,051s
sys	0m42,326s
```

**Comment by ferringb** [comment]
@mgorny if you can still trigger this, I'd be curious as to what your FD limits are, and how parallel you went for the regen.

Additionally, I'm not entirely sure what the code should actually do here beyond fail.

**Comment by arthurzam** [comment]
https://github.com/pkgcore/pkgcore/commit/ce1173fe24f8466a23c502a52af38cdab42353a2
