### ISSUE TITLE
Using profile-formats = portage-2 leads to parsing error when profiles/package.mask dir is dropped

### ISSUE THREAD

**Issue by a17r** [pkgcore/pkgcore#299]
```
gentoo -- updating eclass cache: xorg-3             
kde -- updating eclass cache: kde.org    
kde -- updating git cache: commit date: 2021-03-04
gentoo -- updating profiles cache: x86            
pkgcheck scan: error: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pkgcheck/pipeline.py", line 202, in _run_checks
    results.extend(pipe.run(restrict))
  File "/usr/lib/python3.9/site-packages/pkgcheck/pipeline.py", line 312, in run
    for item in self.source.itermatch(restrict):
  File "/usr/lib/python3.9/site-packages/pkgcheck/sources.py", line 198, in itermatch
    yield Profile(ProfileNode(root), set(files))
  File "/usr/lib/python3.9/site-packages/snakeoil/caching.py", line 120, in __call__
    instance = super(native_WeakInstMeta, cls).__call__(*a, **kw)
  File "/usr/lib/python3.9/site-packages/pkgcore/ebuild/profiles.py", line 138, in __init__
    raise NonexistentProfile(self.path)
pkgcore.ebuild.profiles.NonexistentProfile: failed parsing '/var/db/repos/kde/profiles/package.mask': nonexistent profile directory
```

**Comment by radhermit** [comment]
Fixed in https://github.com/pkgcore/pkgcheck/commit/77a44082dd04ee1472f10ffec0c3b47c868beba9.
