### ISSUE TITLE
Gentoo Prefix (macOS): Sync results in "AttributeError: dlsym(0x10a4598f0, unshare): symbol not found"

### ISSUE THREAD

**Issue by thesamesam** [pkgcore/pkgcore#301]
In trying to resolve https://github.com/pkgcore/pkgdev/issues/30 on macOS (Gentoo Prefix), I thought I'd look at [pconfig dump](https://pkgcore.github.io/pkgcore/man/pkgcore.html#basics-querying) and go from there to see how to configure pkgcore.

Anyway, I tried syncing to see what happened and got a crash.

```
$ mkdir -p /Users/sam/.cache/pkgcore/repos/gentoo
$ pmaint sync
*** syncing gentoo
*** synced gentoo
*** syncing gentoo-sqfs
[============                                      ] 25%
[==================================================] 100%
Traceback (most recent call last):
  File "/Users/sam/Gentoo/usr/lib/python-exec/python3.9/pmaint", line 4, in <module>
    scripts.run(basename(__file__))
  File "/Users/sam/Gentoo/usr/lib/python3.9/site-packages/pkgcore/scripts/__init__.py", line 32, in run
    sys.exit(tool())
  File "/Users/sam/Gentoo/usr/lib/python3.9/site-packages/snakeoil/cli/tool.py", line 79, in __call__
    ret = self.main()
  File "/Users/sam/Gentoo/usr/lib/python3.9/site-packages/snakeoil/cli/tool.py", line 185, in main
    self.handle_exec_exception(e)
  File "/Users/sam/Gentoo/usr/lib/python3.9/site-packages/snakeoil/cli/tool.py", line 170, in main
    exitstatus = func(self.options, self.out, self.err)
  File "/Users/sam/Gentoo/usr/lib/python3.9/site-packages/pkgcore/scripts/pmaint.py", line 71, in sync_main
    ret = repo.operations.sync(
  File "/Users/sam/Gentoo/usr/lib/python3.9/site-packages/pkgcore/operations/__init__.py", line 69, in _recast_exception_decorator
    return functor(*args, **kwds)
  File "/Users/sam/Gentoo/usr/lib/python3.9/site-packages/pkgcore/operations/repo.py", line 147, in _cmd_api_sync
    self.repo._post_sync()
  File "/Users/sam/Gentoo/usr/lib/python3.9/site-packages/pkgcore/ebuild/repo_objs.py", line 1037, in _post_sync
    self._mount_archive()
  File "/Users/sam/Gentoo/usr/lib/python3.9/site-packages/pkgcore/ebuild/repo_objs.py", line 1053, in _mount_archive
    simple_unshare(**unshare_kwds)
  File "/Users/sam/Gentoo/usr/lib/python3.9/site-packages/snakeoil/process/namespaces.py", line 283, in simple_unshare
    create_userns()
  File "/Users/sam/Gentoo/usr/lib/python3.9/site-packages/snakeoil/process/namespaces.py", line 250, in create_userns
    unshare(CLONE_NEWUSER)
  File "/Users/sam/Gentoo/usr/lib/python3.9/site-packages/snakeoil/process/namespaces.py", line 66, in unshare
    if libc.unshare(ctypes.c_int(flags)) != 0:
  File "/Users/sam/Gentoo/usr/lib/python3.9/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/Users/sam/Gentoo/usr/lib/python3.9/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x10d8208f0, unshare): symbol not found
```

```
$ pconfig dump
Traceback (most recent call last):
  File "/Users/sam/Gentoo/usr/lib/python-exec/python3.9/pconfig", line 4, in <module>
    scripts.run(basename(__file__))
  File "/Users/sam/Gentoo/usr/lib/python3.9/site-packages/pkgcore/scripts/__init__.py", line 32, in run
    sys.exit(tool())
  File "/Users/sam/Gentoo/usr/lib/python3.9/site-packages/snakeoil/cli/tool.py", line 79, in __call__
    ret = self.main()
  File "/Users/sam/Gentoo/usr/lib/python3.9/site-packages/snakeoil/cli/tool.py", line 185, in main
    self.handle_exec_exception(e)
  File "/Users/sam/Gentoo/usr/lib/python3.9/site-packages/snakeoil/cli/tool.py", line 169, in main
    self.options, func = self.parse_args(args=self.args, namespace=self.options)
  File "/Users/sam/Gentoo/usr/lib/python3.9/site-packages/snakeoil/cli/tool.py", line 124, in parse_args
    self.handle_exec_exception(e)
  File "/Users/sam/Gentoo/usr/lib/python3.9/site-packages/snakeoil/cli/tool.py", line 100, in parse_args
    options = self.parser.parse_args(args=args, namespace=namespace)
  File "/Users/sam/Gentoo/usr/lib/python3.9/site-packages/snakeoil/cli/arghparse.py", line 1214, in parse_args
    delayed(args, attr)
  File "/Users/sam/Gentoo/usr/lib/python3.9/site-packages/snakeoil/cli/arghparse.py", line 357, in __call__
    self.invokable(namespace, attr)
  File "/Users/sam/Gentoo/usr/lib/python3.9/site-packages/pkgcore/util/commandline.py", line 514, in store_config
    config = load_config(
  File "/Users/sam/Gentoo/usr/lib/python3.9/site-packages/pkgcore/config/__init__.py", line 44, in load_config
    configs.append(PortageConfig(
  File "/Users/sam/Gentoo/usr/lib/python3.9/site-packages/pkgcore/ebuild/portage_conf.py", line 184, in __init__
    repo = repo_cls(
  File "/Users/sam/Gentoo/usr/lib/python3.9/site-packages/pkgcore/ebuild/portage_conf.py", line 639, in _repo_sqfs_v1
    kwargs['repo_obj'] = repo_objs.SquashfsRepoConfig(sqfs_file, repo_path, repo_name)
  File "/Users/sam/Gentoo/usr/lib/python3.9/site-packages/snakeoil/caching.py", line 120, in __call__
    instance = super(WeakInstMeta, cls).__call__(*a, **kw)
  File "/Users/sam/Gentoo/usr/lib/python3.9/site-packages/pkgcore/ebuild/repo_objs.py", line 1020, in __init__
    self._mount_archive()
  File "/Users/sam/Gentoo/usr/lib/python3.9/site-packages/pkgcore/ebuild/repo_objs.py", line 1053, in _mount_archive
    simple_unshare(**unshare_kwds)
  File "/Users/sam/Gentoo/usr/lib/python3.9/site-packages/snakeoil/process/namespaces.py", line 283, in simple_unshare
    create_userns()
  File "/Users/sam/Gentoo/usr/lib/python3.9/site-packages/snakeoil/process/namespaces.py", line 250, in create_userns
    unshare(CLONE_NEWUSER)
  File "/Users/sam/Gentoo/usr/lib/python3.9/site-packages/snakeoil/process/namespaces.py", line 66, in unshare
    if libc.unshare(ctypes.c_int(flags)) != 0:
  File "/Users/sam/Gentoo/usr/lib/python3.9/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/Users/sam/Gentoo/usr/lib/python3.9/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x10a4598f0, unshare): symbol not found
```

**Comment by radhermit** [comment]
pkgcore itself has near zero prefix support since no one has ever cared (see https://github.com/pkgcore/pkgcore/issues/170).
