### ISSUE TITLE
error: repos.conf: default repo 'gentoo' is undefined or invalid

### ISSUE THREAD

**Issue by thesamesam** [pkgcore/pkgcore#303]
Noticed when trying to use NATTkA on a ~sparc Gentoo system. I get 'error: repos.conf: default repo 'gentoo' is undefined or invalid' when trying to use NATTkA or pkgcore directly.

```
# emerge -pvO pkgcore pkgcheck snakeoil nattka

These are the packages that would be merged, in order:

[ebuild   R    ] sys-apps/pkgcore-0.11.8::gentoo  USE="-test" PYTHON_TARGETS="python3_8 python3_9" 0 KiB
[ebuild   R    ] dev-util/pkgcheck-0.9.7::gentoo  USE="-test" PYTHON_TARGETS="python3_8 python3_9" 0 KiB
[ebuild   R    ] dev-python/snakeoil-0.9.6::gentoo  USE="-test" PYTHON_TARGETS="python3_8 python3_9" 0 KiB
[ebuild   R    ] app-portage/nattka-0.2.12::gentoo  USE="(-depgraph-order) -doc -test" PYTHON_TARGETS="python3_8 python3_9" 0 KiB

Total: 4 packages (4 reinstalls), Size of downloads: 0 KiB
```

```
# nattka apply -a sparc 732316
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.9/nattka", line 33, in <module>
    sys.exit(load_entry_point('nattka==0.2.12', 'console_scripts', 'nattka')())
  File "/usr/lib/python3.9/site-packages/nattka/__main__.py", line 1002, in setuptools_main
    sys.exit(main(sys.argv[1:]))
  File "/usr/lib/python3.9/site-packages/nattka/__main__.py", line 993, in main
    return getattr(cmd, args.command.replace('-', '_'))()
  File "/usr/lib/python3.9/site-packages/nattka/__main__.py", line 236, in apply
    repo = self.get_repository()
  File "/usr/lib/python3.9/site-packages/nattka/__main__.py", line 163, in get_repository
    self.domain, self.repo = find_repository(
  File "/usr/lib/python3.9/site-packages/nattka/package.py", line 126, in find_repository
    c = load_config(
  File "/usr/lib/python3.9/site-packages/pkgcore/config/__init__.py", line 44, in load_config
    configs.append(PortageConfig(
  File "/usr/lib/python3.9/site-packages/pkgcore/ebuild/portage_conf.py", line 164, in __init__
    repos_conf_defaults, repos_conf = self.load_repos_conf(
  File "/usr/lib/python3.9/site-packages/pkgcore/ebuild/portage_conf.py", line 388, in load_repos_conf
    raise config_errors.UserConfigError(
pkgcore.config.errors.UserConfigError: repos.conf: default repo 'gentoo' is undefined or invalid
```
```
# pconfig dump
pconfig dump: error: repos.conf: default repo 'gentoo' is undefined or invalid
```

```
# cat /etc/portage/make.conf
COMMON_FLAGS="-O2 -mcpu=ultrasparc -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

CHOST="sparc64-unknown-linux-gnu"

PORTDIR="/bound/portage"
DISTDIR="/bound/distfiles"
LC_MESSAGES=C
ACCEPT_KEYWORDS="~sparc"
RUBY_TARGETS="ruby26 ruby27"

source /bound/conf/make.conf
```

```
# cat /etc/portage/repos.conf/*
[local]
location = /var/db/repos/local
```

```
# cat /usr/share/portage/config/repos.conf
[DEFAULT]
main-repo = gentoo

[gentoo]
location = /var/db/repos/gentoo
sync-type = rsync
sync-uri = rsync://rsync.gentoo.org/gentoo-portage
auto-sync = yes
sync-rsync-verify-jobs = 1
sync-rsync-verify-metamanifest = yes
sync-rsync-verify-max-age = 24
sync-openpgp-key-path = /usr/share/openpgp-keys/gentoo-release.asc
sync-openpgp-keyserver = hkps://keys.gentoo.org
sync-openpgp-key-refresh-retry-count = 40
sync-openpgp-key-refresh-retry-overall-timeout = 1200
sync-openpgp-key-refresh-retry-delay-exp-base = 2
sync-openpgp-key-refresh-retry-delay-max = 60
sync-openpgp-key-refresh-retry-delay-mult = 4
sync-webrsync-verify-signature = yes
```

```
Portage 3.0.17 (python 3.9.2-final-0, default/linux/sparc/17.0/64ul, gcc-10.2.0, glibc-2.32-r8, 5.10.12-gentoo sparc)
=================================================================
System uname: Linux-5.10.12-gentoo-sparc-sun4v-with-glibc2.32
KiB Mem:   531343128 total, 490493912 free
KiB Swap:          0 total,         0 free
Timestamp of repository gentoo: Sun, 28 Mar 2021 14:05:43 +0000
sh bash 5.1_p4
ld GNU ld (Gentoo 2.35.2 p1) 2.35.2
app-shells/bash:          5.1_p4::gentoo
dev-lang/perl:            5.32.1::gentoo
dev-lang/python:          2.7.18_p7::gentoo, 3.8.8::gentoo, 3.9.2::gentoo
dev-util/cmake:           3.20.0::gentoo
sys-apps/baselayout:      2.7-r1::gentoo
sys-apps/openrc:          0.42.1-r1::gentoo
sys-apps/sandbox:         2.22::gentoo
sys-devel/autoconf:       2.13-r1::gentoo, 2.69-r5::gentoo
sys-devel/automake:       1.16.3-r1::gentoo
sys-devel/binutils:       2.35.2::gentoo
sys-devel/gcc:            10.2.0-r5::gentoo
sys-devel/gcc-config:     2.4::gentoo
sys-devel/libtool:        2.4.6-r6::gentoo
sys-devel/make:           4.3::gentoo
sys-kernel/linux-headers: 5.11::gentoo (virtual/os-headers)
sys-libs/glibc:           2.32-r8::gentoo
Repositories:

gentoo
    location: /bound/portage
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000
    sync-rsync-extra-opts:
    sync-rsync-verify-metamanifest: yes
    sync-rsync-verify-max-age: 24
    sync-rsync-verify-jobs: 1

local
    location: /var/db/repos/local
    masters: gentoo

ACCEPT_KEYWORDS="sparc ~sparc"
ACCEPT_LICENSE="@FREE"
CBUILD="sparc64-unknown-linux-gnu"
CFLAGS="-O2 -mcpu=ultrasparc -pipe -fdiagnostics-show-option -frecord-gcc-switches"
CHOST="sparc64-unknown-linux-gnu"
CONFIG_PROTECT="/etc /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo /etc/texmf/language.dat.d /etc/texmf/language.def.d /etc/texmf/updmap.d /etc/texmf/web2c"
CXXFLAGS="-O2 -mcpu=ultrasparc -pipe"
DISTDIR="/bound/distfiles"
EMERGE_DEFAULT_OPTS="--complete-graph --with-bdeps=y --keep-going --deep"
ENV_UNSET="CARGO_HOME DBUS_SESSION_BUS_ADDRESS DISPLAY GOBIN GOPATH PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR"
FCFLAGS="-O2 -mcpu=ultrasparc -pipe"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs binpkg-multi-instance cgroup config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync network-sandbox news parallel-fetch pid-sandbox preserve-libs protect-owned qa-unresolved-soname-deps sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -mcpu=ultrasparc -pipe"
GENTOO_MIRRORS="http://distfiles.gentoo.org"
LANG="C.UTF8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu"
MAKEOPTS="-j150 -l257"
PKGDIR="/var/cache/binpkgs"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
USE="X acl berkdb big-endian bzip2 caps cli crypt dbus dri elogind filecaps fortran gdbm gmp iconv introspection ipv6 jit libglvnd libtirpc ncurses nls nptl openmp pam pcre polkit readline sparc split-usr ssl tcpd unicode xattr zlib" ADA_TARGET="gnat_2018" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="karbon sheets words" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock greis isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" INPUT_DEVICES="libinput" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" LUA_SINGLE_TARGET="lua5-1" LUA_TARGETS="lua5-1" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php7-3 php7-4" POSTGRES_TARGETS="postgres10 postgres11" PYTHON_SINGLE_TARGET="python3_8" PYTHON_TARGETS="python3_8 python3_9" RUBY_TARGETS="ruby26 ruby27" USERLAND="GNU" VIDEO_CARDS="fbdev glint mga r128 radeon dummy v4l" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq proto steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CC, CPPFLAGS, CTARGET, CXX, INSTALL_MASK, LC_ALL, LINGUAS, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS
```

**Comment by thesamesam** [comment]
What I can't understand is another chroot works fine and I haven't modified anything recently AFAIK.

From the working stable sparc chroot:
```
[ebuild   R    ] dev-util/pkgcheck-0.9.3-r1::gentoo  USE="-test" PYTHON_TARGETS="python3_8 python3_9" 0 KiB
[ebuild   R    ] sys-apps/pkgcore-0.11.5-r2::gentoo  USE="-test" PYTHON_TARGETS="python3_8 python3_9" 0 KiB
[ebuild   R    ] dev-python/snakeoil-0.9.4::gentoo  USE="-test" PYTHON_TARGETS="python3_8 python3_9" 0 KiB
```

```
# pconfig dump
'basic' {
    # typename of this section: pmerge_formatter
    class pkgcore.ebuild.formatter.BasicFormatter;
}


'fetcher' {
    # typename of this section: fetcher
    class pkgcore.fetch.custom.fetcher;
    # type: int
    # attempts = 10 of unknown type int
    # type: str
    command 'wget -t 3 -T 60 --passive-ftp -O "${DISTDIR}/${FILE}" "${URI}"';
    # type: str
    distdir '/bound/distfiles';
    # type: str
    resume_command 'wget -c -t 3 -T 60 --passive-ftp -O "${DISTDIR}/${FILE}" "${URI}"';
}

'installed' {
    # typename of this section: pkgset
    class pkgcore.pkgsets.installed.Installed;
    # type: refs:repo
    vdb 'vdb';
}

'livefs' {
    # typename of this section: domain
    class pkgcore.ebuild.domain.domain;
    default true;
    # type: str
    ACCEPT_LICENSE '*';
    # type: str
    ACCEPT_PROPERTIES '*';
    # type: str
    ACCEPT_RESTRICT '*';
    # type: str
    CFLAGS '-O2 -mcpu=ultrasparc -pipe -fdiagnostics-show-option -frecord-gcc-switches';
    # type: str
    CHOST 'sparc64-unknown-linux-gnu';
    # type: str
    CLEAN_DELAY '0';
    # type: str
    COMMON_FLAGS '-O2 -mcpu=ultrasparc -pipe';
    # type: str
    CXXFLAGS '-O2 -mcpu=ultrasparc -pipe';
    # type: str
    EMERGE_DEFAULT_OPTS '--complete-graph --with-bdeps=y --keep-going --deep';
    # type: str
    FCFLAGS '-O2 -mcpu=ultrasparc -pipe';
    # type: str
    FEATURES 'protect-owned sandbox sfperms strict unmerge-orphans\n\tuserfetch userpriv usersandbox usersync sandbox strict cgroup pid-sandbox';
    # type: str
    FFLAGS '-O2 -mcpu=ultrasparc -pipe';
    # type: str
    LC_MESSAGES 'C';
    # type: str
    LDFLAGS ' -Wl,--hash-style=gnu';
    # type: str
    MAKEOPTS '-j150 -l257';
    # type: str
    PORTAGE_ELOG_CLASSES ' qa';
    # type: str
    PORTAGE_IONICE_COMMAND 'ionice -c 3 -p ${PID}';
    # type: str
    PORTAGE_NICENESS '19';
    # type: str
    PORTAGE_TMPDIR '/var/tmp';
    # type: str
    PORTDIR '/bound/portage';
    # type: str
    RUBY_TARGETS 'ruby25 ruby26';
    # type: str
    USE ' X dbus elogind X elogind X elogind -static-libs introspection dbus polkit caps seccomp filecaps gmp jit elogind dbus X -bindist';
    # type: str
    config_dir '/etc/portage';
    # type: ref:fetcher
    fetcher 'fetcher';
    # type: str
    name 'livefs';
    # type: ref:profile
    profile 'profile';
    # type: lazy_refs:repo
    repos;
    # type: str
    root '/';
    # type: lazy_refs:repo
    vdb 'vdb';
}

'paludis' {
    # typename of this section: pmerge_formatter
    class pkgcore.ebuild.formatter.PaludisFormatter;
}

'pkgcore' {
    # typename of this section: pmerge_formatter
    class pkgcore.ebuild.formatter.PkgcoreFormatter;
}

'portage' {
    # typename of this section: pmerge_formatter
    class pkgcore.ebuild.formatter.PortageFormatter;
    default true;
}

'portage-verbose' {
    # typename of this section: pmerge_formatter
    class pkgcore.ebuild.formatter.PortageVerboseFormatter;
}

'profile' {
    # typename of this section: profile
    class pkgcore.ebuild.profiles.UserProfile;
    # type: str
    parent_path '/bound/portage/profiles';
    # type: str
    parent_profile 'default/linux/sparc/17.0/64ul/desktop';
    # type: str
    user_path '/etc/portage/profile';
}

'system' {
    # typename of this section: pkgset
    class pkgcore.pkgsets.system.SystemSet;
    # type: ref:profile
    profile 'profile';
}

'vdb' {
    # typename of this section: repo
    class pkgcore.vdb.ondisk.tree;
    # type: str
    cache_location '/var/cache/edb/dep/var/db/pkg';
    # type: str
    location '/var/db/pkg';
}

'versioned-installed' {
    # typename of this section: pkgset
    class pkgcore.pkgsets.installed.VersionedInstalled;
    # type: refs:repo
    vdb 'vdb';
}

'world' {
    # typename of this section: pkgset
    class pkgcore.pkgsets.filelist.WorldFile;
    # type: str
    location '/var/lib/portage/world';
}
```

**Comment by 2xsaiko** [comment]
> ```
> # cat /etc/portage/repos.conf/*
> [local]
> location = /var/db/repos/local
> ```

Pretty sure the gentoo repo needs to be defined in here. At least, the [AMD64 handbook makes you copy][1] /usr/share/portage/config/repos.conf. Don't think it would be different for sparc.

[1]: https://wiki.gentoo.org/wiki/Handbook:AMD64/Installation/Base#Gentoo_ebuild_repository

**Comment by radhermit** [comment]
Closing since this isn't a bug as pkgcore doesn't read ``/usr/share/portage/config/repos.conf`` at all and if ``/etc/portage/repos.conf/*`` exists will need to have all repos defined there that you intend to access.
