### ISSUE TITLE
AttributeError: 'EbuildProcessor' object has no attribute 'pid'

### ISSUE THREAD

**Issue by daviessm** [pkgcore/pkgcore#306]
`pkgcore` v0.11.6-r1
`portage` v3.0.18

```
# pmerge -au @world
 * Resolving...
[ebuild     U  ] dev-python/setuptools-54.2.0 [54.1.1]
[ebuild     U  ] sys-process/glances-3.1.6.2 [3.1.4.1-r1] PYTHON_TARGETS="(-pypy3%) -python3_9%"
[ebuild     U  ] sys-process/htop-3.0.5 [3.0.2] USE="-debug% -hwloc% -lm-sensors%"
[ebuild     U  ] dev-util/debugedit-4.16.1.3 [4.16.1.2]
[ebuild     U  ] app-emulation/qemu-5.2.0-r3 [5.2.0-r2]

 * Running sanity checks...
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.8/pmerge", line 4, in <module>
    scripts.run(basename(__file__))
  File "/usr/lib/python3.8/site-packages/pkgcore/scripts/__init__.py", line 32, in run
    sys.exit(tool())
  File "/usr/lib/python3.8/site-packages/snakeoil/cli/tool.py", line 79, in __call__
    ret = self.main()
  File "/usr/lib/python3.8/site-packages/snakeoil/cli/tool.py", line 185, in main
    self.handle_exec_exception(e)
  File "/usr/lib/python3.8/site-packages/snakeoil/cli/tool.py", line 170, in main
    exitstatus = func(self.options, self.out, self.err)
  File "/usr/lib/python3.8/site-packages/pkgcore/scripts/pmerge.py", line 824, in main
    sanity_failures = run_sanity_checks((x.pkg for x in changes), domain, threads=1)
  File "/usr/lib/python3.8/site-packages/pkgcore/ebuild/misc.py", line 564, in run_sanity_checks
    for pkg, failed in executor.map(sanity_check, _filter_pkgs(pkgs)):
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/site-packages/pkgcore/ebuild/misc.py", line 554, in <lambda>
    sanity_check = lambda pkg_ops: pkg_ops.sanity_check()
  File "/usr/lib/python3.8/site-packages/pkgcore/operations/__init__.py", line 69, in _recast_exception_decorator
    return functor(*args, **kwds)
  File "/usr/lib/python3.8/site-packages/pkgcore/operations/format.py", line 104, in _cmd_api_sanity_check
    return self._cmd_implementation_sanity_check(self.domain)
  File "/usr/lib/python3.8/site-packages/pkgcore/ebuild/ebd.py", line 900, in _cmd_implementation_sanity_check
    result = check(self, self.pkg, domain=domain)
  File "/usr/lib/python3.8/site-packages/pkgcore/ebuild/ebd.py", line 945, in _check_pkg_pretend
    run_generic_phase(
  File "/usr/lib/python3.8/site-packages/pkgcore/ebuild/ebd.py", line 467, in run_generic_phase
    ebd = request_ebuild_processor(userpriv=userpriv, sandbox=sandbox, fd_pipes=fd_pipes)
  File "/usr/lib/python3.8/site-packages/pkgcore/ebuild/processor.py", line 49, in _inner
    return functor(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkgcore/ebuild/processor.py", line 107, in request_ebuild_processor
    ebp = EbuildProcessor(userpriv, sandbox, fd_pipes=fd_pipes)
  File "/usr/lib/python3.8/site-packages/pkgcore/ebuild/processor.py", line 329, in __init__
    signal.signal(signal.SIGTERM, partial(chuck_TermInterrupt, None))
  File "/usr/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
Exception ignored in: <function EbuildProcessor.__del__ at 0x7f050e2a7700>
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pkgcore/ebuild/processor.py", line 771, in __del__
  File "/usr/lib/python3.8/site-packages/pkgcore/ebuild/processor.py", line 676, in is_responsive
  File "/usr/lib/python3.8/site-packages/pkgcore/ebuild/processor.py", line 659, in is_alive
AttributeError: 'EbuildProcessor' object has no attribute 'pid'```

**Comment by radhermit** [comment]
Closing since I'm pretty sure this was fixed in a newer release and git HEAD.
