### ISSUE TITLE
'pmaint regen' hangs after (failed) cache update for 'raw' repository

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcore#314]
```
$ pmaint --config ~/data/etc/portage regen -t 32 -v raw
 * sys-cluster/k3m-9999: failed sourcing ebuild:
 * ERROR: sys-cluster/k3m-9999:: failed (depend phase):
 *   autotools: EAPI 4 not supported
 * 
 * Call stack:
 *          isolated-functions.bash, line 333:  called source '/var/lib/repo-mirror-ci/repos/raw/sys-cluster/k3m/k3m-9999.ebuild'
 *                  k3m-9999.ebuild, line   5:  called inherit 'eutils' 'autotools' 'git-r3'
 *    ebuild-default-functions.bash, line 207:  called __internal_inherit 'autotools'
 *           ebuild-daemon-lib.bash, line 118:  called __qa_invoke 'source' '/var/lib/repo-mirror-ci/repos/gentoo/eclass/autotools.eclass'
 *          isolated-functions.bash, line 333:  called source '/var/lib/repo-mirror-ci/repos/gentoo/eclass/autotools.eclass'
 *                 autotools.eclass, line  35:  called die
 * 
 * Working directory: '/usr/lib64/pkgcore/ebd'
 * sys-cluster/kerrighed-9999-r2: failed sourcing ebuild:
 * ERROR: sys-cluster/kerrighed-9999-r2:: failed (depend phase):
 *   autotools: EAPI 4 not supported
 * 
 * Call stack:
 *          isolated-functions.bash, line 333:  called source '/var/lib/repo-mirror-ci/repos/raw/sys-cluster/kerrighed/kerrighed-9999-r2.ebuild'
 *         kerrighed-9999-r2.ebuild, line   2:  called inherit 'eutils' 'autotools' 'git-r3'
 *    ebuild-default-functions.bash, line 207:  called __internal_inherit 'autotools'
 *           ebuild-daemon-lib.bash, line 118:  called __qa_invoke 'source' '/var/lib/repo-mirror-ci/repos/gentoo/eclass/autotools.eclass'
 *          isolated-functions.bash, line 333:  called source '/var/lib/repo-mirror-ci/repos/gentoo/eclass/autotools.eclass'
 *                 autotools.eclass, line  35:  called die
 * 
 * Working directory: '/usr/lib64/pkgcore/ebd'
 * sys-kernel/next-sources-9999: failed sourcing ebuild:
/var/lib/repo-mirror-ci/repos/raw/eclass/kernel-2.eclass: line 6: PORTAGE_ECLASS_LOCATIONS: bad array subscript
 * sys-kernel/torvalds-sources-9999: failed sourcing ebuild:
/var/lib/repo-mirror-ci/repos/raw/eclass/kernel-2.eclass: line 6: PORTAGE_ECLASS_LOCATIONS: bad array subscript
finished 56 nodes in 2.94 seconds
```

It seems that 4 ebuild-daemon instances remain running.

gdb:
```
#0  0x00007f65934cff87 in wait4 () from /lib64/libc.so.6
#1  0x00007f6593775959 in os_waitpid () from /usr/lib64/libpython3.8.so.1.0
#2  0x00007f659369bce3 in cfunction_vectorcall_FASTCALL () from /usr/lib64/libpython3.8.so.1.0
#3  0x00007f659363bbad in call_function () from /usr/lib64/libpython3.8.so.1.0
[...]
```

**Comment by mgorny** [comment]
Ok, it happens with other repos too and I'm pretty sure it's #307 again.

**Comment by mgorny** [comment]
Or maybe there are two different problems.

**Comment by radhermit** [comment]
Hah, I guess surface level hacks aren't going to cut it that easily. While I'd prefer to rework the metadata regen functionality to be more sane (e.g. use a more recent standard lib thread pool implementation) in addition to fixing this if I had time, it's probably easiest to revert to setting the signal handlers at a global level, move triggering pytest plugin imports into function scope, and ignore other potential 3rd party breakage since I don't think many are importing the related module atm. IIRC, I think one of your previous patches mostly did this.

**Comment by mgorny** [comment]
No, it isn't fixed. Can you reproduce it?

Basically:

```
eselect repository add raw git https://github.com/mahatma-kaganovich/raw.git
pmaint sync raw
pmaint regen -v raw
```

**Comment by radhermit** [comment]
Yep, I can reproduce that now, thanks.
