### ISSUE TITLE
pkgcore-9999 fails to emerge (AttributeError: type object 'EclassDoc' has no attribute 'ABI_VERSION')

### ISSUE THREAD

**Issue by thesamesam** [pkgcore/pkgcore#334]
```
Traceback (most recent call last):
  File "/Users/sam/Gentoo/var/tmp/portage/dev-util/pkgcheck-9999/work/pkgcheck-9999-python3_8/src/pkgcheck/objects.py", line 83, in _dict
    result = getattr(_defaults, self._attr)
AttributeError: 'object' object has no attribute 'KEYWORDS'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 182, in <module>
    setup(**dict(
  File "/Users/sam/Gentoo/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/Users/sam/Gentoo/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/sam/Gentoo/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/sam/Gentoo/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/sam/Gentoo/usr/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/Users/sam/Gentoo/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/sam/Gentoo/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 170, in run
    from pkgcheck.bash import build_library
  File "/Users/sam/Gentoo/var/tmp/portage/dev-util/pkgcheck-9999/work/pkgcheck-9999-python3_8/src/pkgcheck/__init__.py", line 3, in <module>
    from .api import keywords, scan
  File "/Users/sam/Gentoo/var/tmp/portage/dev-util/pkgcheck-9999/work/pkgcheck-9999-python3_8/src/pkgcheck/api.py", line 9, in <module>
    from . import objects
  File "/Users/sam/Gentoo/var/tmp/portage/dev-util/pkgcheck-9999/work/pkgcheck-9999-python3_8/src/pkgcheck/objects.py", line 190, in <module>
    KEYWORDS = _KeywordsLazyDict('KEYWORDS', ('checks', 'results.Result'))
  File "/Users/sam/Gentoo/var/tmp/portage/dev-util/pkgcheck-9999/work/pkgcheck-9999-python3_8/src/pkgcheck/objects.py", line 78, in __init__
    self._dict
  File "/Users/sam/Gentoo/usr/lib/python3.8/site-packages/snakeoil/klass.py", line 176, in __get__
    obj = self.function(instance)
  File "/Users/sam/Gentoo/var/tmp/portage/dev-util/pkgcheck-9999/work/pkgcheck-9999-python3_8/src/pkgcheck/objects.py", line 85, in _dict
    result = _find_obj_classes(*self._func_args)
  File "/Users/sam/Gentoo/var/tmp/portage/dev-util/pkgcheck-9999/work/pkgcheck-9999-python3_8/src/pkgcheck/objects.py", line 47, in _find_obj_classes
    module = import_module(f'.{module_name}', 'pkgcheck')
  File "/Users/sam/Gentoo/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/sam/Gentoo/var/tmp/portage/dev-util/pkgcheck-9999/work/pkgcheck-9999-python3_8/src/pkgcheck/checks/__init__.py", line 10, in <module>
    from .. import addons, base, feeds, runners, sources
  File "/Users/sam/Gentoo/var/tmp/portage/dev-util/pkgcheck-9999/work/pkgcheck-9999-python3_8/src/pkgcheck/feeds.py", line 3, in <module>
    from . import base, sources
  File "/Users/sam/Gentoo/var/tmp/portage/dev-util/pkgcheck-9999/work/pkgcheck-9999-python3_8/src/pkgcheck/sources.py", line 17, in <module>
    from .addons.eclass import Eclass, EclassAddon
  File "/Users/sam/Gentoo/var/tmp/portage/dev-util/pkgcheck-9999/work/pkgcheck-9999-python3_8/src/pkgcheck/addons/eclass.py", line 48, in <module>
    class EclassAddon(caches.CachedAddon):
  File "/Users/sam/Gentoo/var/tmp/portage/dev-util/pkgcheck-9999/work/pkgcheck-9999-python3_8/src/pkgcheck/addons/eclass.py", line 53, in EclassAddon
    version=EclassDoc.ABI_VERSION)
AttributeError: type object 'EclassDoc' has no attribute 'ABI_VERSION'
 * ERROR: dev-util/pkgcheck-9999::gentoo_prefix failed (compile phase):
 *   (no error message)
```

[build.log](https://github.com/pkgcore/pkgcore/files/7836023/build.log)

**Comment by thesamesam** [comment]
oh, nevermind, `@preserved-rebuild` didn't get things in the right order because it has no reason to know newer snakeoil and such is needed, I guess.
