### ISSUE TITLE
AttributeError: module 'pkgcore.ebuild.atom' has no attribute 'valid_use_flag'

### ISSUE THREAD

**Issue by blshkv** [pkgcore/pkgcore#391]
the latest git:
```
bash$ cd /var/db/repos/gentoo/net-analyzer/nmap (just a random package, the same error for any other as well)
bash$ pkgcheck scan
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkgcheck/addons/__init__.py", line 288, in init_addon
    addon = addons_map[cls]
KeyError: <class 'pkgcheck.checks.metadata.IuseCheck'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.10/pkgcheck", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/pkgcheck/scripts/__init__.py", line 46, in main
    run(os.path.basename(sys.argv[0]))
  File "/usr/lib/python3.10/site-packages/pkgcheck/scripts/__init__.py", line 38, in run
    sys.exit(tool())
  File "/usr/lib/python3.10/site-packages/snakeoil/cli/tool.py", line 81, in __call__
    ret = self.main()
  File "/usr/lib/python3.10/site-packages/pkgcheck/cli.py", line 21, in main
    return super().main()
  File "/usr/lib/python3.10/site-packages/snakeoil/cli/tool.py", line 191, in main
    self.handle_exec_exception(e)
  File "/usr/lib/python3.10/site-packages/snakeoil/cli/tool.py", line 176, in main
    exitstatus = func(self.options, self.out, self.err)
  File "/usr/lib/python3.10/site-packages/pkgcheck/scripts/pkgcheck_scan.py", line 450, in _scan
    pipe = Pipeline(options)
  File "/usr/lib/python3.10/site-packages/pkgcheck/pipeline.py", line 36, in __init__
    self._pipes = self._create_runners()
  File "/usr/lib/python3.10/site-packages/pkgcheck/pipeline.py", line 92, in _create_runners
    checks = init_checks(
  File "/usr/lib/python3.10/site-packages/pkgcheck/checks/__init__.py", line 189, in init_checks
    addon = addons.init_addon(cls, options, addons_map)
  File "/usr/lib/python3.10/site-packages/pkgcheck/addons/__init__.py", line 302, in init_addon
    addon = addons_map[cls] = cls(options, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkgcheck/checks/metadata.py", line 213, in __init__
    self.valid_use = atom_mod.valid_use_flag.match
AttributeError: module 'pkgcore.ebuild.atom' has no attribute 'valid_use_flag'
```

/etc/portage/make.profile/parent
```
/var/db/repos/gentoo/profiles/default/linux/amd64/17.1/hardened
/var/db/repos/gentoo/profiles/targets/desktop/plasma
/var/db/repos/pentoo-overlay/profiles/pentoo/overlay
```

**Comment by thesamesam** [comment]
This looks a lot like https://github.com/pkgcore/pkgcheck/commit/5870fb301a195c17d481af90a3669e9ee8338085 / https://github.com/pkgcore/pkgcheck/issues/502.

Are you sure you have the latest versions of the whole stack? 9999 versions won't ensure they have 9999s of others at the latest commit. Try smart-live-rebuild?

**Comment by blshkv** [comment]
ah, sorry, I installed pkgcore-9999 only. It works fine with pkgcheck-9999.

False positive.

**Comment by thesamesam** [comment]
np, thanks for testing from git!
