### ISSUE TITLE
pmaint regen: error: x11-drivers/xf86-video-r128-6.12.1: invalid package name       

### ISSUE THREAD

**Issue by thesamesam** [pkgcore/pkgcore#421]
In `x11-drivers/xf86-video-r128` at ::gentoo commit `b923be7a4099bd8a50ca0991fe3c88f7966eab7d`, I get:
```
$ pkgcheck scan
pkgcheck scan: error: Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pkgcore/ebuild/atom.py", line 298, in __init__
    sf(self, "_cpv", cpv.CPV(self.cpvstr, versioned=bool(self.op)))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pkgcore/ebuild/cpv.py", line 333, in __init__
    raise InvalidCPV(cpvstr, "invalid package name")
pkgcore.ebuild.errors.InvalidCPV: x11-drivers/xf86-video-r128-6.12.1: invalid package name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pkgcheck/pipeline.py", line 231, in _run
    self._queue_work(sync_pipes, work_q)
  File "/usr/lib/python3.12/site-packages/pkgcheck/pipeline.py", line 173, in _queue_work
    for restrict in versioned_source.itermatch(restriction):
  File "/usr/lib/python3.12/site-packages/pkgcheck/sources.py", line 398, in itermatch
    new = self.keyfunc(pkg)
          ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pkgcheck/packages.py", line 34, in versioned_atom
    return atom.atom(f"={self}")
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/snakeoil/caching.py", line 114, in __call__
    instance = super(WeakInstMeta, cls).__call__(*a, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pkgcore/ebuild/atom.py", line 300, in __init__
    raise errors.MalformedAtom(orig_atom) from e
pkgcore.ebuild.errors.MalformedAtom: invalid package atom: '=x11-drivers/xf86-video-r128-6.12.1'
```

With `pmaint regen`, I get:
```
pmaint regen: error: x11-drivers/xf86-video-r128-6.12.1: invalid package name  
```

**Comment by ferringb** [comment]
This is caused by https://github.com/pkgcore/pkgcore/pull/420 ; the fix intended in that PR is correct, it's just tripping on PMS rules slightly.

PMS rules are the package name must not be parse-able as a version, and this includes *the optional revision*.  That PR extended revision awareness, but it wasn't restricted to version + revision.

@thesamesam you can get around this via reverting https://github.com/pkgcore/pkgcore/pull/420/commits/62db14d3ebaa7a2992fd8f8cc7a21126dffef1f7 .  I'll cut a patch later today.
