### ISSUE TITLE
loading a profile with a package.keywords directory fails

### ISSUE THREAD

**Issue by vapier** [pkgcore/pkgcore#82]
to reproduce:
```
$ mkdir /usr/portage/profiles/base/package.keywords
$ python -c 'import pkgcore.config; config = pkgcore.config.load_config(); config.get_default("domain")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/pkgcore/config/central.py", line 568, in get_default
    "Failed instantiating default %s %r" % (type_name, defaults[0][0])))
  File "/usr/lib64/python2.7/site-packages/pkgcore/config/central.py", line 563, in get_default
    return defaults[0][1].instantiate()
  File "/usr/lib64/python2.7/site-packages/pkgcore/config/central.py", line 146, in instantiate
    compatibility.raise_from(errors.InstantiationError(self.name))
  File "/usr/lib64/python2.7/site-packages/pkgcore/config/central.py", line 142, in instantiate
    self._instance = self._instantiate()
  File "/usr/lib64/python2.7/site-packages/pkgcore/config/central.py", line 214, in _instantiate
    "exception caught from %r" % (errors._identify_functor_source(self.type.callable),)))
  File "/usr/lib64/python2.7/site-packages/pkgcore/config/central.py", line 209, in _instantiate
    self._instance = callable_obj(*pargs, **configdict)
  File "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/domain.py", line 280, in __init__
    self.arch, default_keywords, accept_keywords, profile.keywords,
  File "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/profiles.py", line 606, in keywords
    return tuple(chain.from_iterable(x.keywords for x in self.stack))
  File "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/profiles.py", line 606, in <genexpr>
    return tuple(chain.from_iterable(x.keywords for x in self.stack))
  File "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/profiles.py", line 88, in _load_and_invoke
    "path is a directory, but this profile is PMS format- "
  File "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/profiles.py", line 84, in _load_and_invoke
    data = read_func(base, True, True, True)
  File "/usr/lib64/python2.7/site-packages/snakeoil/_fileutils.py", line 97, in native_readlines
    handle = open(mypath, mode)
pkgcore.config.errors.ConfigurationError: Failed instantiating default domain 'livefs domain'
```

also another example of the underlying error being eaten by the config module

**Comment by radhermit** [comment]
I agree the error isn't helpful, but also it appears you're loading a PMS profile which doesn't support directories for various settings like package.keywords. You'll need at least portage-1 in the profile-formats set in the repo's layout.conf file.

**Comment by vapier** [comment]
i wasn't doing it on purpose :) -- there was a stale empty dir that cvs hadn't pruned on me

**Comment by radhermit** [comment]
I don't think this should be an issue anymore as mentioned previously as long as profile-formats has the right options set.
